Repository atk4/data, pull requests merged in 2019-06, with the labels that each got.

#399 Implements User Actions as per wiki
  .github_changelog_generator
  src/Model.php
  src/UserAction/Generic.php
  tests/UserActionTest.php
Labels: MAJOR, in review

#436 CSV persistence should sanitize headers / field names
  src/Persistence.php
  src/Persistence/CSV.php
Labels: Saasty.io :building_construction:, in review

#440 Add support, specifying which fields can be dirty during action call.
  src/Model.php
  src/UserAction/Generic.php
  tests/UserActionTest.php
Labels: Documentation, Tests, in review
