Repository atk4/data, pull requests merged in 2019-05, with the labels that each got.

#412 Feature/contains one many 2
  .codeclimate.yml
  src/Field.php
  src/Field/Boolean.php
  src/Model.php
  src/Persistence.php
  src/Persistence/ArrayOfStrings.php
  src/Persistence/Array_.php
  src/Persistence/SQL.php
  src/Reference.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/FieldTest.php
  tests/PersistentArrayOfStringsTest.php
Labels: Saasty.io :building_construction:, enhancement, in review

#421 implement action(field) for array persistence, fix #415
  src/Persistence/Array_.php
  tests/PersistentArrayTest.php
Labels: in review

#414 should solve bug #698
  src/Field.php
Labels: in progress

#431 Nesty BUG. was still returning wrong
  src/Field.php
Labels: in review

#413 add condition if ref(hasOne) model not loaded
  src/Reference/HasOne_SQL.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/ReferenceSQLTest.php
Labels: in progress

#430 Implements DeepCopy->transformData()
  src/Util/DeepCopy.php
Labels: in review

#419 Improving documentation of Model
  docs/hooks.rst
  docs/model.rst
  docs/persistence.rst
  docs/results.rst
Labels: in review
