Repository atk4/data, pull requests merged in 2019-12, with the labels that each got.

#486 Feature/pgsql test
  composer.json
  tests/DeepCopyTest.php
Labels: in progress

#492 Add matrix testing
  .github/release-drafter.yml
  .github/workflows/bundler.yml
  .github/workflows/unit-tests.yml
  .old.travis.yml
Labels: enhancement

#490 Feature/set custom edit exec button
  src/Model.php
Labels: question
