Repository atk4/data, pull requests merged in 2020-05, with the labels that each got.

#585 move lastInsertID to persistence
  src/Model.php
  src/Persistence/SQL.php
Labels: in review

#596 Remove NameTrait trait from Model
  src/Model.php
Labels: BC-break

#601 add documentation for Model::setNull()
  docs/fields.rst
  docs/model.rst
Labels: Documentation
