Repository atk4/data, pull requests merged in 2020-07, with the labels that each got.

#652 Fix PSR class/trait/method naming
  README.md
  docs/conditions.rst
  docs/fields.rst
  docs/hooks.rst
  docs/joins.rst
  docs/model.rst
  docs/persistence.rst
  docs/persistence/csv.rst
  docs/quickstart.rst
  docs/references.rst
  docs/sql.rst
  docs/typecasting.rst
  src/Field.php
  src/FieldSql.php
  src/FieldSqlExpression.php
  src/Join.php
  src/Join/Sql.php
  src/Model.php
  src/Model/UserAction.php
  src/Persistence.php
  src/Persistence/Array_.php
  src/Persistence/Csv.php
  src/Persistence/Sql.php
  src/Reference.php
  src/Reference/ContainsOne.php
  src/Reference/HasOneSql.php
  tests/ConditionSqlTest.php
  tests/CsvTest.php
  tests/DeepCopyTest.php
  tests/ExpressionSqlTest.php
  tests/FieldTest.php
  tests/FolderTest.php
  tests/IteratorTest.php
  tests/JoinSqlTest.php
  tests/LimitOrderTest.php
  tests/LocaleTest.php
  tests/LookupSqlTest.php
  tests/ModelWithoutIdTest.php
  tests/PersistentSqlTest.php
  tests/RandomTest.php
  tests/ReadOnlyModeTest.php
  tests/ReferenceSqlTest.php
  tests/SerializeTest.php
  tests/StaticPersistenceTest.php
  tests/SubTypesTest.php
  tests/TransactionTest.php
  tests/TypecastingTest.php
  tests/UserActionTest.php
  tests/WithTest.php
  tests/_Template.php
Labels: BC-break, Refactoring

#654 Drop AppScopeTrait trait from Model & Persistence classes
  src/Model.php
  src/Persistence.php
Labels: BC-break, RTM

#621 Add separate/explicit Model::setMulti() method, Model::set() no longer accepts array
  docs/model.rst
  docs/persistence.rst
  docs/quickstart.rst
  src/Model.php
  tests/BusinessModelTest.php
  tests/ContainsOneTest.php
  tests/PersistentArrayOfStringsTest.php
  tests/PersistentArrayTest.php
  tests/TransactionTest.php
  tests/TypecastingTest.php
Labels: BC-break

#567 Enforce array in method prototypes when appropriate
  src/Action/Iterator.php
  src/Join.php
  src/Model.php
  src/Persistence.php
  src/Persistence/Array_.php
  src/Persistence/Csv.php
  src/Persistence/Sql.php
  tests/PersistentArrayTest.php
  tests/ValidationTest.php
Labels: BC-break

#657 Fix composer develop install issue
  .github/workflows/bundler.yml
  composer.json
Labels: RTM

#658 Fix composer.json
  composer.json
Labels: RTM

#659 Fix Iterator data types
  src/Action/Iterator.php
Labels: RTM

#660 Use Scope class for filtering/where impl. for Model
  docs/conditions.rst
  src/Action/Iterator.php
  src/Model.php
  src/Model/Scope.php
  src/Model/Scope/AbstractCondition.php
  src/Model/Scope/BasicCondition.php
  src/Model/Scope/CompoundCondition.php
  src/Persistence/Array_.php
  src/Persistence/Sql.php
  src/Persistence/Static_.php
  tests/ConditionSqlTest.php
  tests/ConditionTest.php
  tests/PersistentArrayTest.php
  tests/PersistentSqlTest.php
  tests/ReferenceSqlTest.php
  tests/ScopeTest.php
Labels: MAJOR

#667 Fix Scope::createXx bug
  src/Model/Scope.php
Labels: bug

#663 Rename BasicCondition to Condition
  docs/conditions.rst
  src/Action/Iterator.php
  src/Model/Scope/CompoundCondition.php
  src/Model/Scope/Condition.php
  src/Persistence/Sql.php
  tests/ScopeTest.php
Labels: Refactoring

#664 Scope improve usability - addCondition() should not wrap
  src/Model/Scope/CompoundCondition.php
  src/Model/Scope/Condition.php
  tests/ScopeTest.php
Labels: Refactoring

#674 Fix typo in phpdoc in Scope class
  src/Model/Scope.php
Labels: RTM
