Repository atk4/data, pull requests merged in 2020-06, with the labels that each got.

#597 Convert callables to closures and move hook names to constants
  docs/advanced.rst
  docs/design.rst
  docs/hooks.rst
  docs/model.rst
  docs/overview.rst
  docs/persistence.rst
  src/Field/Callback.php
  src/Field_SQL_Expression.php
  src/Join.php
  src/Join/Array_.php
  src/Join/SQL.php
  src/Model.php
  src/Persistence.php
  src/Persistence/SQL.php
  src/Persistence/Static_.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  src/Reference/HasOne.php
  src/Reference/HasOne_SQL.php
  src/Util/DeepCopy.php
  tests/DeepCopyTest.php
  tests/FieldTest.php
  tests/JoinSQLTest.php
  tests/LookupSQLTest.php
  tests/Model/Smbo/Transfer.php
  tests/RandomTest.php
  tests/SubTypesTest.php
  tests/TransactionTest.php
  tests/ValidationTest.php
Labels: BC-break

#591 Isolate ArrayAccess from Model to optional/BC trait
  README.md
  docs/advanced.rst
  docs/conditions.rst
  docs/design.rst
  docs/expressions.rst
  docs/fields.rst
  docs/hooks.rst
  docs/joins.rst
  docs/model.rst
  docs/overview.rst
  docs/persistence.rst
  docs/quickstart.rst
  docs/references.rst
  docs/results.rst
  docs/sql.rst
  docs/typecasting.rst
  docs/types.rst
  src/Join/Array_.php
  src/Join/SQL.php
  src/Model.php
  src/ModelArrayAccessTrait.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  src/Reference/HasMany.php
  src/Reference/HasOne.php
  src/Reference/HasOne_SQL.php
  src/Util/DeepCopy.php
  tests/BusinessModelTest.php
  tests/CSVTest.php
  tests/ConditionSQLTest.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/DeepCopyTest.php
  tests/ExpressionSQLTest.php
  tests/FieldHereditaryTest.php
  tests/FieldTest.php
  tests/FieldTypesTest.php
  tests/IteratorTest.php
  tests/JoinArrayTest.php
  tests/JoinSQLTest.php
  tests/JoinTest.php
  tests/LookupSQLTest.php
  tests/Model/Smbo/Account.php
  tests/Model/Smbo/Transfer.php
  tests/ModelWithoutIDTest.php
  tests/PersistentArrayTest.php
  tests/PersistentSQLTest.php
  tests/RandomTest.php
  tests/ReadOnlyModeTest.php
  tests/ReferenceSQLTest.php
  tests/ReferenceTest.php
  tests/SmboTransferTest.php
  tests/StaticPersistenceTest.php
  tests/SubTypesTest.php
  tests/TransactionTest.php
  tests/TypecastingTest.php
  tests/UserActionTest.php
  tests/ValidationTest.php
Labels: BC-break, Cleanup

#565 Allow to add() only an object
  docs/fields.rst
  docs/model.rst
  src/Join.php
  src/Model.php
  src/Persistence.php
  src/Persistence/Array_.php
  src/Persistence/SQL.php
  tests/FieldTest.php
  tests/PersistentArrayTest.php
  tests/SmboTransferTest.php
Labels: BC-break

#607 Refactor exception constructor calls to not use array
  docs/advanced.rst
  docs/hooks.rst
  docs/persistence.rst
  docs/sql.rst
  src/Field.php
  src/Join.php
  src/Join/Array_.php
  src/Model.php
  src/Persistence.php
  src/Persistence/Array_.php
  src/Persistence/CSV.php
  src/Persistence/SQL.php
  src/Persistence/Static_.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  src/Reference/HasMany.php
  src/Reference/HasOne_SQL.php
  src/UserAction/Generic.php
  src/Util/DeepCopy.php
  tests/RandomTest.php
Labels: RTM

#604 Remove support of default field + do not explode CSV string/value
  docs/typecasting.rst
  src/Action/Iterator.php
  src/Field/Email.php
  src/Model.php
  src/ValidationException.php
  tests/BusinessModelTest.php
  tests/CSVTest.php
  tests/DeepCopyTest.php
  tests/FieldTest.php
  tests/LimitOrderTest.php
  tests/LookupSQLTest.php
  tests/RandomTest.php
  tests/SmboTransferTest.php
  tests/SubTypesTest.php
  tests/ValidationTest.php
Labels: BC-break, RTM

#561 Upgrade phpunit
  composer.json
  src/Field.php
  src/Join.php
  src/Model.php
  tests/BusinessModelTest.php
  tests/ConditionSQLTest.php
  tests/ConditionTest.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/DeepCopyTest.php
  tests/FieldTest.php
  tests/IteratorTest.php
  tests/JoinArrayTest.php
  tests/JoinSQLTest.php
  tests/JoinTest.php
  tests/LimitOrderTest.php
  tests/LocaleTest.php
  tests/LookupSQLTest.php
  tests/ModelWithoutIDTest.php
  tests/PersistentArrayTest.php
  tests/RandomTest.php
  tests/ReadOnlyModeTest.php
  tests/ReferenceSQLTest.php
  tests/ReferenceTest.php
  tests/SerializeTest.php
  tests/TypecastingTest.php
  tests/UserActionTest.php
  tests/ValidationTest.php
  tests/WithTest.php
Labels: RTM, help wanted

#615 Revert mandatory validation known-bug (as before phpunit upgrade)
  src/Field.php
  src/Field/Email.php
  tests/FieldTest.php
Labels: RTM

#619 Fix tests - exception message changed in atk4/core
  tests/UserActionTest.php
Labels: RTM

#620 Fix typo - ModelArrayAccessTrait is trait (not class)
  src/ModelArrayAccessTrait.php
Labels: RTM

#616 HasXxx() methods now return bool only + always require field to be defined first
  docs/model.rst
  docs/references.rst
  src/Join.php
  src/Join/Array_.php
  src/Join/SQL.php
  src/Model.php
  src/Persistence.php
  src/Persistence/Array_.php
  src/Persistence/CSV.php
  src/Persistence/SQL.php
  src/Util/DeepCopy.php
  tests/BusinessModelTest.php
  tests/ConditionTest.php
  tests/FieldTest.php
  tests/ReferenceSQLTest.php
  tests/UserActionTest.php
Labels: BC-break, RTM

#613 Better fix for null offset limit
  src/Persistence/SQL.php
Labels: RTM

#623 Add codecov.yml config
  README.md
  codecov.yml
Labels: RTM

#628 Fix tests when SqlFormatter formatter lib is available
  tests/WithTest.php
Labels: RTM

#627 Improve array persistence and disallow passing array by reference
  src/Action/Iterator.php
  src/Persistence.php
  src/Persistence/Array_.php
  src/Persistence/CSV.php
  src/Persistence/Static_.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  tests/JoinArrayTest.php
  tests/JoinTest.php
  tests/PersistentArrayTest.php
  tests/ReferenceTest.php
  tests/ValidationTest.php
Labels: BC-break, RTM

#637 [update] use dsql refactored connection class
  src/Persistence/SQL.php
Labels: RTM

#639 Use strict array seed
  docs/model.rst
  src/Model.php
  src/Persistence/Array_.php
  src/Persistence/SQL.php
  src/Reference.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/FieldTypesTest.php
  tests/RandomTest.php
Labels: RTM

#640 Fix default action icon seeds
  src/Model.php
Labels: RTM

#642 fix reference
  src/Reference.php
Labels: RTM

#634 [refactor] UserAction\Generic to Model\UserAction
  docs/model.rst
  src/Model.php
  src/Model/HasUserActionsTrait.php
  src/Model/UserAction.php
  src/UserAction/Generic.php
  tests/UserActionTest.php
Labels: BC-break, Clarity, Refactoring
