Repository atk4/data, pull requests merged in 2020-09, with the labels that each got.

#697 Convert Model to Entity (prevent reload with a different record)
  src/Model.php
  src/Persistence/Csv.php
  tests/ConditionSqlTest.php
  tests/ContainsManyTest.php
  tests/CsvTest.php
  tests/ExpressionSqlTest.php
  tests/FieldTest.php
  tests/JoinArrayTest.php
  tests/JoinSqlTest.php
  tests/LookupSqlTest.php
  tests/PersistentArrayTest.php
  tests/PersistentSqlTest.php
  tests/ReferenceSqlTest.php
  tests/SmboTransferTest.php
  tests/SubTypesTest.php
  tests/TypecastingTest.php
Labels: BC-break, MAJOR, RTM, enhancement

#703 Fix missing Model::reload_after_save restore
  .php_cs.dist
  phpunit-mysql.xml.dist
  phpunit-pgsql.xml.dist
  phpunit.xml.dist
  src/Field.php
  src/Model.php
  src/Model/UserAction.php
  src/Persistence/Sql.php
Labels: RTM

#709 On-the-fly transform of ID in array persistance from key to result data
  src/Field.php
  src/Model.php
  src/Persistence/Array_.php
  src/Persistence/Csv.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  tests/JoinArrayTest.php
  tests/PersistentArrayOfStringsTest.php
  tests/PersistentArrayTest.php
Labels: Consistency, RTM

#706 Fix PostgreSQL CI errors
  .github/workflows/unit-tests.yml
  docs/persistence.rst
  src/Persistence/Sql.php
  tests/ConditionSqlTest.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/DeepCopyTest.php
  tests/FieldTest.php
  tests/JoinSqlTest.php
  tests/ModelWithoutIdTest.php
  tests/RandomTest.php
  tests/ReferenceSqlTest.php
  tests/SmboTransferTest.php
  tests/SubTypesTest.php
  tests/TypecastingTest.php
Labels: RTM

#708 Drop ID property in advance of standard row data, provide BC using magic
  docs/persistence.rst
  src/Model.php
  src/Persistence/Csv.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  tests/ContainsOneTest.php
  tests/CsvTest.php
  tests/ModelWithoutIdTest.php
  tests/PersistentSqlTest.php
  tests/ReadOnlyModeTest.php
  tests/ReferenceTest.php
  tests/UserActionTest.php
Labels: BC-break, bug

#717 Drop $from_persistence support for Model::load()
  src/Model.php
Labels: BC-break, Consistency

#718 Fix issues with dirty ID
  src/Model.php
  src/Persistence/Sql.php
Labels: RTM, bug

#716 Drop magic ID property from Model
  README.md
  docs/advanced.rst
  docs/expressions.rst
  docs/hooks.rst
  docs/joins.rst
  docs/model.rst
  docs/persistence.rst
  docs/quickstart.rst
  docs/references.rst
  docs/sql.rst
  src/Model.php
  src/Model/UserAction.php
  src/Persistence/Array_.php
  src/Persistence/Sql.php
  src/Persistence/Sql/Join.php
  src/Reference/HasMany.php
  src/Reference/HasOne.php
  src/Util/DeepCopy.php
  tests/BusinessModelTest.php
  tests/DeepCopyTest.php
  tests/JoinSqlTest.php
  tests/Model/Smbo/Account.php
  tests/Model/Smbo/Transfer.php
  tests/ModelWithoutIdTest.php
  tests/PersistentSqlTest.php
  tests/RandomTest.php
  tests/ReferenceTest.php
  tests/SmboTransferTest.php
  tests/SubTypesTest.php
  tests/TypecastingTest.php
  tests/_Template.php
Labels: BC-break, Consistency, MAJOR, RTM, enhancement

#720 Stricter Condition validation, remove legacy OR condition support
  src/Model.php
  src/Model/Scope/Condition.php
  tests/ConditionSqlTest.php
  tests/ConditionTest.php
  tests/PersistentArrayTest.php
  tests/ScopeTest.php
Labels: BC-break, Consistency, help wanted

#719 Add MSSQL support
  .github/workflows/unit-tests.yml
  phpunit-mssql.xml.dist
  src/Model.php
  src/Persistence.php
  src/Persistence/Sql.php
  src/Util/DeepCopy.php
  tests/DeepCopyTest.php
  tests/JoinSqlTest.php
  tests/RandomTest.php
  tests/ReferenceSqlTest.php
  tests/WithTest.php
Labels: RTM, waitingForAnotherPR

#723 Add Oracle DB support
  .github/workflows/unit-tests.yml
  phpunit-oracle.xml.dist
  src/Model/Join.php
  src/Persistence/Sql.php
  tests/ExpressionSqlTest.php
  tests/JoinSqlTest.php
  tests/ReferenceSqlTest.php
  tests/TypecastingTest.php
  tests/WithTest.php
Labels: RTM

#631 Update CS - require strict comparison
  .php_cs.dist
  src/Action/Iterator.php
  src/Field.php
  src/Model.php
  src/Model/Scope.php
  src/Model/Scope/Condition.php
  src/Persistence/Array_.php
  src/Persistence/Sql.php
  tests/BusinessModelTest.php
  tests/ModelWithoutIdTest.php
  tests/ScopeTest.php
  tests/TypecastingTest.php
Labels: RTM

#726 Revert to official Docker image
  .github/workflows/unit-tests.yml
Labels: RTM

#730 fix Model::addFields() with field object
  src/Model.php
Labels: RTM, bug

#731 Fix array persistence - addIdToLoadRow() must be called on data passed by-reference
  src/Persistence/Array_.php
  tests/PersistentArrayOfStringsTest.php
  tests/PersistentArrayTest.php
Labels: RTM, bug

#732 Remove persistence override support from Model::load/save/atomic methods
  src/Model.php
Labels: BC-break, Consistency, RTM

#711 Fix not rebound hooks after clone
  docs/advanced.rst
  docs/design.rst
  docs/model.rst
  docs/persistence.rst
  src/Field.php
  src/Field/Callback.php
  src/FieldSql.php
  src/FieldSqlExpression.php
  src/Model.php
  src/Model/Join.php
  src/Persistence/Array_/Join.php
  src/Persistence/Sql.php
  src/Persistence/Sql/Join.php
  src/Persistence/Static_.php
  src/Reference.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  src/Reference/HasOne.php
  src/Reference/HasOneSql.php
  tests/DeepCopyTest.php
  tests/FieldTest.php
  tests/JoinSqlTest.php
  tests/LookupSqlTest.php
  tests/Model/Smbo/Transfer.php
  tests/RandomTest.php
  tests/SubTypesTest.php
  tests/TransactionTest.php
  tests/ValidationTest.php
Labels: BC-break, MAJOR, RTM, bug

#715 Add loadany() to Array_ Persistence
  src/Persistence/Array_.php
  tests/PersistentArrayTest.php
Labels: waitingForAnotherPR

#735 Add smoke and burn CI testing
  .github/workflows/unit-tests.yml
  composer.json
  phpunit-mssql.xml.dist
  phpunit-mysql.xml.dist
  phpunit-oracle.xml.dist
  phpunit-pgsql.xml.dist
  phpunit.xml.dist
  src/Action/Iterator.php
Labels: RTM

#737 Fix GC for CallbackFilterIterator using WeakReference
  .github/workflows/unit-tests.yml
  src/Action/Iterator.php
  tests/CsvTest.php
Labels: RTM
