Repository atk4/data, pull requests merged in 2020-11, with the labels that each got.

#772 Improve debug - dump params
  src-schema/PhpunitTestCase.php
Labels: RTM

#774 Fix for dsql - do not compare dsql/Expression on Model::set()
  src/Model.php
Labels: RTM

#773 Enable CLOB tests for Oracle, support fixed in dsql
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
Labels: RTM, waitingForAnotherPR

#776 Fix comment - PostgreSQL requires PK specified in SQL to use autoincrement
  tests/ModelWithoutIdTest.php
Labels: RTM

#775 Improve assertion of statically quoted SQLs
  src-schema/PhpunitTestCase.php
  tests/RandomTest.php
  tests/ReferenceSqlTest.php
  tests/WithTest.php
Labels: RTM

#780 Use new Factory methods
  src/Model.php
  src/Model/UserActionsTrait.php
  src/Persistence.php
  src/Reference.php
Labels: RTM

#779 LOB to string is handled in dsql
  src/Persistence/ArrayOfStrings.php
  src/Persistence/Sql.php
Labels: RTM

#783 Improve UserAction properties access
  src/Model/UserAction.php
  tests/UserActionTest.php
Labels: RTM

#786 Should use recursive merging
  src/Field.php
Labels: RTM, bug

#787 Finally fix containsOne/Many UI property overwrites
  src/Reference/ContainsOne.php
Labels: RTM
