Repository atk4/data, pull requests merged in 2020-10, with the labels that each got.

#740 Fix app/owner getters
  docs/advanced.rst
  docs/hooks.rst
  docs/persistence.rst
  docs/sql.rst
  src/Field.php
  src/FieldSqlExpression.php
  src/Model/Join.php
  src/Model/Scope.php
  src/Model/Scope/AbstractScope.php
  src/Model/Scope/Condition.php
  src/Model/UserAction.php
  src/Persistence/Array_/Join.php
  src/Persistence/Sql.php
  src/Persistence/Sql/Join.php
  src/Reference.php
  src/Reference/HasOne.php
Labels: BC-break, RTM

#741 Fix owner prop to getter phpdoc
  src/Field.php
  src/Model/Join.php
  src/Model/Scope/AbstractScope.php
  src/Model/UserAction.php
  src/Reference.php
Labels: RTM

#747 Drop driverType property
  src/Persistence.php
  tests/ConditionSqlTest.php
  tests/DeepCopyTest.php
  tests/ExpressionSqlTest.php
  tests/JoinSqlTest.php
  tests/ModelWithoutIdTest.php
  tests/RandomTest.php
  tests/ReferenceSqlTest.php
  tests/ScopeTest.php
  tests/TypecastingTest.php
  tests/WithTest.php
Labels: BC-break

#748 Integrate atk4/schema into atk4/data
  composer.json
  phpunit-mysql.xml.dist
  phpunit.xml.dist
  src-schema/Migration.php
  src-schema/Migration/Mssql.php
  src-schema/Migration/Mysql.php
  src-schema/Migration/Oracle.php
  src-schema/Migration/Postgresql.php
  src-schema/Migration/Sqlite.php
  src-schema/PhpunitTestCase.php
  tests-schema/BasicTest.php
  tests-schema/ModelTest.php
  tests-schema/PhpunitTestCaseTest.php
Labels: RTM

#749 remove deprecated code for dec-2020
  src-schema/Migration.php
  src/Join.php
  src/Join/Array_.php
  src/Join/Sql.php
  src/Model/UserAction.php
  src/Model/UserActionsTrait.php
  src/Reference.php
  src/UserAction/Generic.php
Labels: RTM

#700 Revert join test fix after join/reference clone is fixed
  docs/joins.rst
  src/Field.php
  src/Model.php
  src/Model/Join.php
  src/Model/JoinLinkTrait.php
  src/Persistence/Array_/Join.php
  src/Persistence/Sql.php
  src/Persistence/Sql/Join.php
  src/Reference/HasOne.php
  tests/JoinSqlTest.php
Labels: BC-break, bug

#752 Rename getTheirModel to createTheirModel
  src/Reference.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  src/Reference/HasMany.php
  src/Reference/HasOne.php
  src/Reference/HasOneSql.php
Labels: BC-break, RTM, Refactoring

#750 Change onHookToOwner to onHookShortToOwner
  src/Field.php
  src/Field/Callback.php
  src/FieldSqlExpression.php
  src/Model.php
  src/Model/Join.php
  src/Persistence/Array_/Join.php
  src/Persistence/Sql/Join.php
Labels: RTM

#753 Replace original atk4/schema with DBAL SchemaManager
  .github/workflows/unit-tests.yml
  composer.json
  src-schema/Migration.php
  src-schema/Migration/Mssql.php
  src-schema/Migration/Mysql.php
  src-schema/Migration/Oracle.php
  src-schema/Migration/Postgresql.php
  src-schema/Migration/Sqlite.php
  src-schema/PhpunitTestCase.php
  src/Model.php
  src/Persistence.php
  src/Persistence/GenericPlatform.php
  src/Persistence/Sql.php
  tests-schema/BasicTest.php
  tests-schema/ModelTest.php
  tests-schema/PhpunitTestCaseTest.php
  tests/ConditionSqlTest.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/ExpressionSqlTest.php
  tests/JoinSqlTest.php
  tests/LookupSqlTest.php
  tests/ModelWithoutIdTest.php
  tests/ReferenceSqlTest.php
  tests/SmboTransferTest.php
Labels: BC-break, MAJOR, RTM, waitingForAnotherPR

#755 Fixes field name in Persistence exceptions
  src/Persistence.php
Labels: RTM

#756 Fixes field name in Persistence exceptions for 2.3 branch
  src/Persistence.php
Labels: RTM

#758 Explicit drop "if exists"
  src-schema/Migration.php
  src-schema/PhpunitTestCase.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/DeepCopyTest.php
  tests/LookupSqlTest.php
  tests/ScopeTest.php
  tests/SmboTransferTest.php
  tests/SubTypesTest.php
Labels: BC-break, RTM

#761 Test using lowest deps
  .github/workflows/unit-tests.yml
Labels: RTM

#763 Fix never thrown PDOException
  docs/hooks.rst
  src/Persistence/Sql.php
Labels: RTM, waitingForAnotherPR

#762 fix phpdoc of _hasReference
  src/Model/ReferencesTrait.php
Labels: RTM

#764 Revert "fix phpdoc of _hasReference"
  src/Model/Join.php
  src/Model/ReferencesTrait.php
  src/Reference.php
Labels: RTM

#765 Fix typo
  .github/workflows/unit-tests.yml
Labels: RTM

#766 Fix default string/text case sensitivity in Migrator
  src-schema/Migration.php
  tests-schema/ModelTest.php
Labels: RTM, bug

#767 Fix Model::import() to be executed in single transaction
  src/Model.php
Labels: RTM, bug

#769 Fix for updated dsql - where wraps
  tests/ExpressionSqlTest.php
Labels: RTM

#771 UserAction->execute() can return value
  src/Model/UserActionsTrait.php
Labels: RTM

#770 Fix for updated dsql - rename Expression::get() to getRows()
  src-schema/PhpunitTestCase.php
  src/Persistence/Sql.php
  tests/ExpressionSqlTest.php
Labels: RTM
