Repository atk4/data, pull requests merged in 2020-08, with the labels that each got.

#686 Fix query on hasOne referenced model
  src/Model.php
  src/Persistence.php
  src/Persistence/Array_.php
  src/Persistence/Sql.php
  src/Reference.php
  src/Reference/ContainsMany.php
  src/Reference/ContainsOne.php
  src/Reference/HasMany.php
  src/Reference/HasOne.php
  src/Reference/HasOneSql.php
  tests/ReferenceSqlTest.php
Labels: bug

#624 Add type validation to factory calls
  src/Model.php
  src/Model/JoinsTrait.php
  src/Model/ReferencesTrait.php
Labels: RTM

#695 Make init() methods protected and fix calls to ->invokeInit()
  docs/advanced.rst
  docs/design.rst
  docs/overview.rst
  docs/quickstart.rst
  src/Field/Boolean.php
  src/Field/Callback.php
  src/FieldSqlExpression.php
  src/Model.php
  src/Model/Join.php
  src/Model/Scope/AbstractScope.php
  src/Model/UserAction.php
  src/Persistence/Array_/Join.php
  src/Persistence/Sql/Join.php
  src/Reference.php
  src/Reference/ContainsOne.php
  src/Reference/HasOne.php
  tests/ContainsManyTest.php
  tests/ContainsOneTest.php
  tests/DeepCopyTest.php
  tests/FolderTest.php
  tests/LookupSqlTest.php
  tests/Model/Client.php
  tests/Model/Female.php
  tests/Model/Male.php
  tests/Model/Person.php
  tests/Model/Smbo/Account.php
  tests/Model/Smbo/Company.php
  tests/Model/Smbo/Contact.php
  tests/Model/Smbo/Document.php
  tests/Model/Smbo/Payment.php
  tests/Model/Smbo/Transfer.php
  tests/Model/User.php
  tests/RandomTest.php
  tests/ScopeTest.php
  tests/StaticPersistenceTest.php
  tests/SubTypesTest.php
  tests/UserActionTest.php
  tests/ValidationTest.php
Labels: BC-break, waitingForAnotherPR
