Repository atk4/data, pull requests merged in 2020-12, with the labels that each got.

#802 Fix reverse join inconsistencies and defaults
  src/Model/Join.php
  tests/JoinArrayTest.php
  tests/JoinSqlTest.php
Labels: RTM

#805 Use short Model name everywhere
  tests/BusinessModelTest.php
  tests/FolderTest.php
  tests/Model/Smbo/Account.php
  tests/Model/Smbo/Contact.php
  tests/Model/Smbo/Document.php
  tests/RandomTest.php
  tests/UserActionTest.php
Labels: Refactoring

#806 Implicit ID have default type of integer and is required by default
  src/Model.php
  tests-schema/ModelTest.php
  tests/RandomTest.php
  tests/SmboTransferTest.php
Labels: BC-break

#810 Remove Model\Base class introduced temporary in PR 800 (hintable support)
  composer.json
  src/Model.php
  src/Model/Base.php
Labels: RTM

#807 Cleanup for DBAL 2.10 and higher
  bootstrap-atk-types.php
Labels: RTM, waitingForAnotherPR

#813 Rename Persistence\Array_::get() method to getRows()
  docs/sql.rst
  src/Action/Iterator.php
  src/Persistence/Array_.php
  tests/PersistentArrayTest.php
Labels: RTM

#811 Change HasOne type to integer by default
  src/Reference/HasOne.php
  tests/RandomTest.php
  tests/ReferenceSqlTest.php
  tests/SmboTransferTest.php
Labels: BC-break

#808 Fix PHPStan Model IteratorAggregate phpdoc
  src/Model.php
  src/Persistence/Array_.php
  src/Persistence/Csv.php
  src/Persistence/Sql.php
Labels: RTM

#816 Adjust Expressionable::getDsqlExpression() prototype
  src/Field.php
  src/FieldSql.php
  src/FieldSqlExpression.php
  src/Persistence/Sql/Join.php
  src/ValidationException.php
Labels: RTM

#814 Improve PHPStan level to 5
  docs/expressions.rst
  phpstan.neon.dist
  src-schema/Migration.php
  src-schema/PhpunitTestCase.php
  src/Action/Iterator.php
  src/Field.php
  src/Model.php
  src/Model/Join.php
  src/Model/JoinsTrait.php
  src/Model/ReferencesTrait.php
  src/Model/Scope.php
  src/Model/Scope/Condition.php
  src/Model/Scope/RootScope.php
  src/Model/UserAction.php
  src/Persistence/Array_/Join.php
  src/Persistence/Csv.php
  src/Persistence/Sql.php
  src/Persistence/Sql/Join.php
  src/Persistence/Static_.php
  src/Reference.php
  tests-schema/ModelTest.php
  tests/BusinessModelTest.php
  tests/ExpressionSqlTest.php
  tests/LimitOrderTest.php
  tests/RandomTest.php
  tests/ValidationTest.php
Labels: BC-break, RTM

#819 Table must be specified with table key in defaults
  docs/quickstart.rst
  src/Model.php
  tests-schema/ModelTest.php
  tests/ConditionSqlTest.php
  tests/ExpressionSqlTest.php
  tests/FieldTest.php
  tests/IteratorTest.php
  tests/JoinArrayTest.php
  tests/JoinSqlTest.php
  tests/LimitOrderTest.php
  tests/LocaleTest.php
  tests/ModelWithoutIdTest.php
  tests/PersistentArrayOfStringsTest.php
  tests/PersistentArrayTest.php
  tests/PersistentSqlTest.php
  tests/RandomTest.php
  tests/ReadOnlyModeTest.php
  tests/ReferenceSqlTest.php
  tests/ReferenceTest.php
  tests/SerializeTest.php
  tests/TransactionTest.php
  tests/TypecastingTest.php
  tests/WithTest.php
  tests/_Template.php
Labels: BC-break

#820 Require array in reference/join defaults
  README.md
  docs/advanced.rst
  docs/design.rst
  docs/references.rst
  docs/sql.rst
  phpstan.neon.dist
  src/Model/Join.php
  src/Model/JoinsTrait.php
  src/Model/ReferencesTrait.php
  tests/ConditionTest.php
  tests/DeepCopyTest.php
  tests/FieldTest.php
  tests/FolderTest.php
  tests/JoinArrayTest.php
  tests/JoinSqlTest.php
  tests/LookupSqlTest.php
  tests/Model/Smbo/Account.php
  tests/Model/Smbo/Document.php
  tests/Model/Smbo/Payment.php
  tests/Model/Smbo/Transfer.php
  tests/PersistentArrayTest.php
  tests/RandomTest.php
  tests/ReferenceSqlTest.php
  tests/ReferenceTest.php
  tests/ScopeTest.php
  tests/SubTypesTest.php
  tests/WithTest.php
Labels: BC-break
