Repository atk4/data, pull requests merged in 2021-03, with the labels that each got.

#837 Add model in ValidationExceptions
  src/Field.php
  src/Field/Boolean.php
  src/Field/Email.php
  src/Persistence.php
  src/ValidationException.php
Labels: RTM

#838 Feature/fix conditions
  src/Persistence/Sql.php
  src/Persistence/Sql/Join.php
Labels: bug

#836 Improve table_alias gen
  src/Model.php
  src/Reference.php
  tests/SubTypesTest.php
Labels: bug

#839 Better num key det
  src/Reference.php
  src/Reference/HasOneSql.php
Labels: Refactoring

#840 PHPStan issue 4267 fixed officially
  .github/workflows/unit-tests.yml
  composer.json
Labels: RTM
